# Generated by Django 3.2.9 on 2021-11-06 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherAverage',
            fields=[
                ('wid', models.AutoField(primary_key=True, serialize=False)),
                ('lo_index', models.IntegerField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('temp_date', models.DateField(blank=True, null=True)),
                ('temp_avg', models.FloatField(blank=True, null=True)),
                ('temp_max', models.FloatField(blank=True, null=True)),
                ('temp_min', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'weather_average',
            },
        ),
    ]
