# Generated by Django 3.2.9 on 2021-11-06 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(null=True, upload_to='Image/Board/')),
                ('like', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
